# Generated by Django 3.2.5 on 2022-01-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_t', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_t', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_t', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.DateTimeField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('good_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品编号')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_t', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_t', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_t', models.DateTimeField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.DateTimeField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('order_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单编号')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
