# Generated by Django 3.2.5 on 2022-01-14 09:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='delete_t',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_delete',
            field=models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delete_t',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除'),
        ),
    ]
