# Generated by Django 3.2.5 on 2022-01-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220115_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='discountscoupons',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='homeadvertising',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='kanjiaset',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='liverooms',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='moneyinfo',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='sitegoodsdynamic',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dataDelete',
            new_name='dateDelete',
        ),
    ]
