# Generated by Django 3.2.5 on 2022-01-18 14:38

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sessioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='dateEndInt',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='秒杀结束时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='dateStartInt',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='秒杀开始时间'),
        ),
    ]
