# Generated by Django 3.2.5 on 2022-01-18 15:14

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220118_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_goods', to='app.goodscategory'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dateEnd',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='结束时间'),
        ),
    ]
