# Generated by Django 3.2.5 on 2022-01-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220118_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_goods', to='app.goodscategory', verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='characteristic',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='minPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='originalPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='recommendStatus',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否下架'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='key',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='标号'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='type',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='类别'),
        ),
    ]
