# Generated by Django 3.2.5 on 2022-01-19 02:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220118_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='dateProduction',
            field=app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='goods',
            name='dayDue',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='剩余过期时间'),
        ),
    ]
