# Generated by Django 3.2.5 on 2022-01-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220119_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='recommendStatus',
            field=models.IntegerField(blank=True, choices=[(0, '普通'), (1, '推荐')], default=0, null=True, verbose_name='是否推荐商品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '下架'), (1, '上架')], default=1, null=True, verbose_name='商品状态'),
        ),
    ]
