# Generated by Django 3.2.5 on 2022-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_goods_daydue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountsCoupons',
        ),
        migrations.DeleteModel(
            name='KanJiaSet',
        ),
        migrations.DeleteModel(
            name='LiveRooms',
        ),
        migrations.DeleteModel(
            name='MoneyInfo',
        ),
        migrations.RenameField(
            model_name='homeadvertising',
            old_name='type',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='notice',
            name='isShow',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=True, null=True, verbose_name='是否在首页显示'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.TextField(blank=True, default='0', max_length=2048, null=True, verbose_name='标题'),
        ),
    ]
