# Generated by Django 3.2.5 on 2022-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220119_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeadvertising',
            name='type',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
