# Generated by Django 3.2.5 on 2022-01-21 06:43

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_homeadvertising_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '小程序配置', 'verbose_name_plural': '小程序配置'},
        ),
        migrations.AlterModelOptions(
            name='homeadvertising',
            options={'verbose_name': '弹窗广告', 'verbose_name_plural': '弹窗广告'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '网站公告', 'verbose_name_plural': '网站公告'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='sessioninfo',
            options={'verbose_name': '微信授权记录', 'verbose_name_plural': '微信授权记录'},
        ),
        migrations.AlterModelOptions(
            name='sitegoodsdynamic',
            options={'verbose_name': '购买动态', 'verbose_name_plural': '购买动态'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='kanjia',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=False, null=True, verbose_name='是否参加砍价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='kanjiaPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='砍价价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='maxCoupons',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最大优惠'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='miaosha',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=False, null=True, verbose_name='是否参加秒杀'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='minBuyNumber',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最少购买数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='minScore',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最低积分'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberGoodReputation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='商品评价人数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberOrders',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='订单数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pingtuan',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=False, null=True, verbose_name='是否拼团'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pingtuanPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='拼团价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='recommendStatusStr',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='推荐状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='seckillBuyNumber',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='商品秒杀数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sellEnd',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=False, null=True, verbose_name='是否停售'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sellStart',
            field=models.BooleanField(blank=True, choices=[(True, '真'), (False, '假')], default=True, null=True, verbose_name='是否开始销售'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shopId',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='商店ID'),
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdd', app.models.TimeStampField(auto_now_add=True, verbose_name='创建时间')),
                ('dateUpdate', app.models.TimeStampField(auto_now=True, verbose_name='更新时间')),
                ('dateDelete', app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('key', models.CharField(blank=True, default='5b2a16e8d15d25b416e87f228b6d50f3', max_length=255, null=True, verbose_name='购物车编号')),
                ('goodsId', models.IntegerField(blank=True, default=0, null=True, verbose_name='商品ID')),
                ('number', models.IntegerField(blank=True, default=1, null=True, verbose_name='商品数量')),
                ('selected', models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=1, null=True, verbose_name='是否选中')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_goods', to='app.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
