# Generated by Django 3.2.5 on 2022-01-21 11:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220121_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdd', app.models.TimeStampField(auto_now_add=True, verbose_name='创建时间')),
                ('dateUpdate', app.models.TimeStampField(auto_now=True, verbose_name='更新时间')),
                ('dateDelete', app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('key', models.CharField(blank=True, default='0', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '微信密钥',
                'verbose_name_plural': '微信密钥',
            },
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='goods',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user_id',
            field=models.CharField(blank=True, default='o', max_length=255, null=True, verbose_name='用户ID'),
        ),
    ]
