# Generated by Django 3.2.5 on 2022-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220121_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculate',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardId',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cityId',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='couponId',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deductionScore',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='districtId',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='goodsJsonStr',
            field=models.JSONField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='goodsType',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='peisongType',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provinceId',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
