# Generated by Django 3.2.5 on 2022-01-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_order_goodsjsonstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goodsJsonStr',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
