# Generated by Django 3.2.5 on 2022-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_order_goodsjsonstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goodsJsonStr',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
