# Generated by Django 3.2.5 on 2022-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_order_goodsjsonstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extJsonStr',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='linkMan',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='goodsJsonStr',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
