# Generated by Django 3.2.5 on 2022-01-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220125_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_close',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pay',
        ),
    ]
