# Generated by Django 3.2.5 on 2022-01-25 08:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220125_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdd', app.models.TimeStampField(auto_now_add=True, verbose_name='创建时间')),
                ('dateUpdate', app.models.TimeStampField(auto_now=True, verbose_name='更新时间')),
                ('dateDelete', app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('address', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('areaStr', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('cityId', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('cityStr', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('districtId', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('isDefault', models.BooleanField(blank=True, default=False, null=True)),
                ('linkMan', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('provinceId', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('provinceStr', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('statusStr', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('uid', models.IntegerField(blank=True, default=0, null=True)),
                ('userId', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user_id',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='用户ID'),
        ),
    ]
