# Generated by Django 3.2.5 on 2022-01-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220125_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userId',
            field=models.CharField(blank=True, default=0, max_length=225, null=True),
        ),
    ]
