# Generated by Django 3.2.5 on 2022-01-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_address_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='calculate',
        ),
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
