# Generated by Django 3.2.5 on 2022-01-27 12:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220127_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdd', app.models.TimeStampField(auto_now_add=True, verbose_name='创建时间')),
                ('dateUpdate', app.models.TimeStampField(auto_now=True, verbose_name='更新时间')),
                ('dateDelete', app.models.TimeStampField(blank=True, default=0, null=True, verbose_name='删除时间')),
                ('is_delete', models.BooleanField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否删除')),
                ('address', models.CharField(blank=True, default='0', max_length=225, null=True, verbose_name='超市地址')),
                ('name', models.CharField(blank=True, default='0', max_length=225, null=True, verbose_name='超市名字')),
                ('linkPhone', models.CharField(blank=True, default='0', max_length=225, null=True, verbose_name='超市联系电话')),
                ('goodsNeedCheck', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='userId',
            field=models.CharField(blank=True, default='0', max_length=225, null=True),
        ),
    ]
