# Generated by Django 3.2.5 on 2022-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220127_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shopName',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
