# Generated by Django 3.2.5 on 2022-01-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220127_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cardId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='couponId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='numbers',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='订单商品总数'),
        ),
        migrations.AddField(
            model_name='order',
            name='prices',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='linkMan',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='备注'),
        ),
    ]
