# Generated by Django 3.2.5 on 2022-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220128_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freight',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_prices',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True, verbose_name='应付价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True, verbose_name='订单商品总数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prices',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True, verbose_name='订单总价'),
        ),
    ]
