# Generated by Django 3.2.5 on 2022-01-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220128_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='freight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_prices',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='应付价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prices',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='订单总价'),
        ),
    ]
