# Generated by Django 3.2.5 on 2022-01-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220128_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='订单商品总数'),
        ),
    ]
