# Generated by Django 3.2.5 on 2022-01-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20220128_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopaddress',
            options={'verbose_name': '超市配置', 'verbose_name_plural': '超市配置'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='areaStr',
        ),
        migrations.RemoveField(
            model_name='address',
            name='cityId',
        ),
        migrations.RemoveField(
            model_name='address',
            name='cityStr',
        ),
        migrations.RemoveField(
            model_name='address',
            name='districtId',
        ),
        migrations.RemoveField(
            model_name='address',
            name='provinceId',
        ),
        migrations.RemoveField(
            model_name='address',
            name='provinceStr',
        ),
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
        migrations.RemoveField(
            model_name='address',
            name='statusStr',
        ),
        migrations.RemoveField(
            model_name='address',
            name='uid',
        ),
    ]
