# Generated by Django 3.2.5 on 2022-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20220128_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='kanjia',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='kanjiaPrice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='maxCoupons',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='miaosha',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='minScore',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='numberFav',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='numberGoodReputation',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='numberReputation',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pingtuan',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pingtuanPrice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='recommendStatus',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='recommendStatusStr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='seckillBuyNumber',
        ),
        migrations.AlterField(
            model_name='goods',
            name='minPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='商品图片'),
        ),
    ]
