import json

from django.http import JsonResponse
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response

from app.models import Goods
from app.paginations import ShortResultsSetPagination
from app.serializers import UserSerializer, GroupSerializer, GoodsSerializer


# Create your views here.
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]


class ConfigList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        json_data = {
            "code": 0,
            "data": [
                {
                    "dateUpdate": "2021-11-01 11:38:01",
                    "key": "wxpay_api_url",
                    "remark": "小程序支付接口URL地址",
                    "value": "/pay/wx/wxapp"
                },
                {
                    "dateUpdate": "2021-08-31 20:11:19",
                    "key": "order_pay_user_balance",
                    "remark": "订单支付允许使用余额",
                    "value": "1"
                },
                {
                    "dateUpdate": "2021-07-22 14:23:49",
                    "key": "orderPeriod_open",
                    "remark": "是否开启订阅模式",
                    "value": "0"
                },
                {
                    "key": "share_pic",
                    "remark": "转发分享的图片",
                    "value": "https://dcdn.it120.cc/2021/06/25/b9ece465-efd1-472e-b42a-add48199941f.jpeg"
                },
                {
                    "dateUpdate": "2021-06-25 18:41:37",
                    "key": "fx_subscribe_ids",
                    "remark": "申请加入分销商的订阅消息模版ID",
                    "value": "7sO58VXh0T5a6SwB5c9hR43bnBPxW8E6v3d70QQXuIk"
                },
                {
                    "key": "show_score_sign",
                    "remark": "是否显示签到送积分模块",
                    "value": "1"
                },
                {
                    "key": "show_score_exchange_growth",
                    "remark": "是否显示积分兑换成长值入口",
                    "value": "1"
                },
                {
                    "key": "show_quan_exchange_score",
                    "remark": "是否显示积分券兑换积分入口",
                    "value": "1"
                },
                {
                    "key": "show_3_seller",
                    "remark": "是否显示三级分销入口",
                    "value": "1"
                },
                {
                    "key": "goods_search_show_type",
                    "remark": "搜索页面商品展现方式，1 为一行1个商品；2为一行2个商品",
                    "value": "1"
                },
                {
                    "key": "show_buy_dynamic",
                    "remark": "是否显示首页的购买动态",
                    "value": "1"
                },
                {
                    "key": "show_seller_number",
                    "remark": "商品是否显示销量",
                    "value": "1"
                },
                {
                    "dateUpdate": "2021-04-11 21:50:41",
                    "key": "recycle_open",
                    "remark": "是否开启回收功能",
                    "value": "1"
                },
                {
                    "dateUpdate": "2021-04-11 21:50:44",
                    "key": "cps_open",
                    "remark": "开启cps功能",
                    "value": "1"
                },
                {
                    "dateUpdate": "2021-07-22 14:46:11",
                    "key": "shopping_cart_vop_open",
                    "remark": "是否开启云货架购物车",
                    "value": "0"
                },
                {
                    "dateUpdate": "2021-03-19 09:48:36",
                    "key": "shipping_address_region_level",
                    "remark": "收货地址省市区县需要几级，只支持3和4",
                    "value": "3"
                },
                {
                    "dateUpdate": "2021-03-19 09:52:14",
                    "key": "shipping_address_gps",
                    "remark": "添加收货地址是否需要选择定位",
                    "value": "0"
                },
                {
                    "dateUpdate": "2021-03-29 15:09:33",
                    "key": "balance_pay_pwd",
                    "remark": "余额消费需要交易密码",
                    "value": "0"
                },
                {
                    "dateUpdate": "2020-11-13 10:08:54",
                    "key": "adminUserIds",
                    "remark": "管理员绑定的用户编号，多个编号用英文逗号分割",
                    "value": "1351478"
                },
                {
                    "dateUpdate": "2020-11-13 10:03:49",
                    "key": "needIdCheck",
                    "remark": "是否需要进行用户实名认证后才可以下单",
                    "value": "0"
                },
                {
                    "dateUpdate": "2020-12-09 18:07:37",
                    "key": "shopMod",
                    "remark": "0为单店铺版本 ； 1为多店铺版本",
                    "value": "0"
                },
                {
                    "dateUpdate": "2020-11-13 09:46:50",
                    "key": "goodsDetailSkuShowType",
                    "remark": "0 为点击立即购买按钮后出现规格尺寸、数量的选择； 1为直接在商品详情页面显示规格尺寸、数量的选择，而不弹框",
                    "value": "0"
                },
                {
                    "key": "share_profile",
                    "remark": "转发小程序时候的话术",
                    "value": "百款精品商品，总有一款适合您"
                },
                {
                    "key": "subscribe_ids",
                    "remark": "订阅号模板ID，多个用英文的逗号分隔",
                    "value": "ITVuuD_cwYN-5BjXne8cSktDo43xetj0u-lpvFZEQQs,dw9Tzh9r0sw7Gjab0ovQJx3bP3gdXmF_FZvpnxPd6hc"
                },
                {
                    "dateUpdate": "2020-03-20 23:55:05",
                    "key": "order_hx_uids",
                    "remark": "核销管理员",
                    "value": "1262609"
                },
                {
                    "dateUpdate": "2020-04-28 21:22:43",
                    "key": "mallName",
                    "remark": "小程序名称",
                    "value": "天使童装"
                }
            ],
            "msg": "success"
        }
        return Response(json_data)


class WxAppAuthorize(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def post(self, request):
        code = request.data.get('code', '093zjbGa17kttC0pC5Ha1D1vSR1zjbG3')
        json_data = {
    "code": 500,
    "msg": "can not get openid"
}
        return Response(json_data)


class BannerList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        type_str = request.query_params.get('type', 'index')
        json_data = {
    "code": 0,
    "data": [
        {
            "businessId": 0,
            "dateAdd": "2019-12-29 09:58:08",
            "dateUpdate": "2020-02-20 09:54:27",
            "id": 49755,
            "linkUrl": "",
            "paixu": 0,
            "picUrl": "https://dcdn.it120.cc/2019/12/29/8396f65d-d615-46d8-b2e5-aa41820b9fe5.png",
            "status": 0,
            "statusStr": "显示",
            "title": "首页轮播图",
            "type": "index",
            "userId": 951
        },
        {
            "businessId": 0,
            "dateAdd": "2019-12-29 09:57:57",
            "dateUpdate": "2020-02-20 09:54:31",
            "id": 49754,
            "paixu": 0,
            "picUrl": "https://dcdn.it120.cc/2019/12/29/daca65ee-4347-4792-a490-ccbac4b3c1d7.png",
            "status": 0,
            "statusStr": "显示",
            "title": "首页轮播图",
            "type": "index",
            "userId": 951
        },
        {
            "businessId": 0,
            "dateAdd": "2019-12-29 09:57:43",
            "dateUpdate": "2020-02-20 09:54:37",
            "id": 49753,
            "paixu": 0,
            "picUrl": "https://dcdn.it120.cc/2019/12/29/2e79921a-92b3-4d1d-8182-cb3d524be5fb.png",
            "status": 0,
            "statusStr": "显示",
            "title": "首页轮播图",
            "type": "index",
            "userId": 951
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class CategoryAll(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        json_data = {
    "code": 0,
    "data": [
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/f89753a227d26a3fe9ccc6f975857bb6.png",
            "id": 1872,
            "isUse": True,
            "key": "1",
            "level": 1,
            "name": "上装",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "index",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/5bfffd6ad0d4483870f024a3ed936528.png",
            "id": 1873,
            "isUse": True,
            "key": "2",
            "level": 1,
            "name": "裤装",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/8d32c254e2cb86d2d42c99b768d136b6.png",
            "id": 1875,
            "isUse": True,
            "key": "4",
            "level": 1,
            "name": "特价区",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/d800327091f216e2c83db8af7b6be306.png",
            "id": 1906,
            "isUse": True,
            "key": "5",
            "level": 1,
            "name": "裙装",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/cfee29650d6ae58a4bb1f84a3d899450.png",
            "id": 1907,
            "isUse": True,
            "key": "6",
            "level": 1,
            "name": "套装",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/6b3136cda73c99453ac93a1c5a9deebf.png",
            "id": 2016,
            "isUse": True,
            "key": "7",
            "level": 1,
            "name": "外套",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/9a7356187fce687ce568ba7381685299.png",
            "id": 2054,
            "isUse": True,
            "key": "8",
            "level": 1,
            "name": "秒杀",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/7773b4c204280ba194514594f7070ac9.png",
            "id": 2245,
            "isUse": True,
            "key": "9",
            "level": 1,
            "name": "内裤",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/60f41bf042d201b48a7115d22344320f.png",
            "id": 2246,
            "isUse": True,
            "key": "10",
            "level": 1,
            "name": "袜子",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        },
        {
            "icon": "https://cdn.it120.cc/apifactory/2019/04/09/cdb16ac9c66bc211b82bd947452526f4.png",
            "id": 2787,
            "isUse": True,
            "key": "11",
            "level": 1,
            "name": "鞋",
            "paixu": 0,
            "pid": 0,
            "shopId": 0,
            "type": "",
            "userId": 951
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class ShopGoodsList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        json_data = {
    "code": 0,
    "data": [
        {
            "afterSale": "0,1,2",
            "categoryId": 1875,
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2021-04-11 22:43:55",
            "dateUpdate": "2022-01-13 21:15:51",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": True,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 810285,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 299.00,
            "minScore": 0,
            "name": "小票打印机工厂定制版",
            "numberFav": 46,
            "numberGoodReputation": 9,
            "numberOrders": 9,
            "numberReputation": 2,
            "numberSells": 9,
            "originalPrice": 0.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://dcdn.it120.cc/2020/04/15/0a86e7ef-3680-4f9f-a22c-2afb26672b7d.png",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "priceShopSell": 0.00,
            "propertyIds": ",30899,30900,30901,",
            "recommendStatus": 1,
            "recommendStatusStr": "推荐",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 6040,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 4999941,
            "stores0Unsale": False,
            "tags": "",
            "type": 0,
            "unit": "台",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 10237,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "brandId": 3,
            "categoryId": 1875,
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2020-05-22 13:33:11",
            "dateUpdate": "2022-01-13 21:36:33",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": True,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 435060,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 499.00,
            "minScore": 0,
            "name": "WiFi云标签机 FP-N20W",
            "numberFav": 117,
            "numberGoodReputation": 14,
            "numberOrders": 14,
            "numberReputation": 0,
            "numberSells": 16,
            "originalPrice": 0.00,
            "overseas": True,
            "paixu": 0,
            "pic": "https://dcdn.it120.cc/2020/05/22/83618213-99b6-42ce-a672-becf466aa515.png",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 1,
            "recommendStatusStr": "推荐",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 9989,
            "stores0Unsale": False,
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 29326,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "6932719822120",
            "brandId": 4,
            "categoryId": 1875,
            "characteristic": "养成刷牙好习惯 保护牙齿",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2019-12-06 11:58:20",
            "dateUpdate": "2022-01-13 16:50:35",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 235853,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 51089,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 9.90,
            "minScore": 100,
            "name": "3分钟沙漏「儿童刷牙计时器」",
            "numberFav": 79,
            "numberGoodReputation": 30,
            "numberOrders": 34,
            "numberReputation": 2,
            "numberSells": 34,
            "originalPrice": 12.96,
            "overseas": False,
            "paixu": 0,
            "pic": "https://dcdn.it120.cc/2019/12/06/ebf49ac6-4521-4bcc-92fd-8bbbd4131167.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "priceShopSell": 0.00,
            "propertyIds": ",869,871,",
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 59879,
            "stores0Unsale": False,
            "subName": "别名啦啦啦",
            "type": 0,
            "unit": "个",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 27754,
            "weight": 1.50
        },
        {
            "afterSale": "0,1,2",
            "barCode": "P123456",
            "categoryId": 2054,
            "commission": 0.02,
            "commissionSettleType": 1,
            "commissionType": 2,
            "commissionUserType": 1,
            "dateAdd": "2019-03-11 13:02:39",
            "dateUpdate": "2022-01-13 18:57:31",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": True,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 122843,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 499.00,
            "minScore": 0,
            "name": "小票打印机工厂定制版",
            "numberFav": 118,
            "numberGoodReputation": 84,
            "numberOrders": 976,
            "numberReputation": 0,
            "numberSells": 958,
            "originalPrice": 0.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://dcdn.it120.cc/2020/04/15/0a86e7ef-3680-4f9f-a22c-2afb26672b7d.png",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "priceShopSell": 0.00,
            "propertyIds": ",30899,30900,30901,",
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 10000005,
            "stores0Unsale": False,
            "tags": "打印机",
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 56048,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "",
            "categoryId": 2016,
            "characteristic": "尼多熊袜子，适合秋冬",
            "commission": 5.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-10-30 10:51:08",
            "dateEnd": "2022-01-08 00:00:00",
            "dateEndPingtuan": "2022-01-10 11:34:26",
            "dateStart": "2022-01-01 19:46:26",
            "dateUpdate": "2022-01-13 20:59:50",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 6765,
            "kanjia": True,
            "kanjiaPrice": 82.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": True,
            "minBuyNumber": 1,
            "minPrice": 100.00,
            "minScore": 0,
            "name": "男童防晒衣夏装薄外套2019年新款童装儿童中大童透气帅洋气休闲潮",
            "numberFav": 2,
            "numberGoodReputation": 2,
            "numberOrders": 4,
            "numberReputation": 0,
            "numberSells": 3,
            "originalPrice": 180.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/07/11/3bfecdf0-16c5-4710-a8e7-dd6880543ece.gif",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "priceShopSell": 0.00,
            "purchaseNotes": "",
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": True,
            "sellStart": True,
            "shopId": 6041,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "storeAlertNum": 10,
            "stores": 999,
            "stores0Unsale": False,
            "tags": "很棒",
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "videoId": "c4c6e38eeb3a428e80f1a8b32c6de587",
            "views": 106174,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "",
            "categoryId": 1872,
            "characteristic": "尼多熊袜子，适合秋冬天",
            "commission": 5.00,
            "commissionSettleType": 0,
            "commissionType": 2,
            "commissionUserType": 0,
            "dateAdd": "2017-10-30 00:00:00",
            "dateEnd": "2022-01-23 11:38:29",
            "dateEndCountDown": "9天",
            "dateEndPingtuan": "2022-01-10 11:35:13",
            "dateStart": "2022-01-03 11:38:27",
            "dateUpdate": "2022-01-13 21:33:51",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 6761,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": True,
            "minBuyNumber": 1,
            "minPrice": 190.00,
            "minScore": 0,
            "name": "儿童睡衣男童短袖纯棉夏季薄款男孩中大童卡通宝宝家居服套装夏天",
            "numberFav": 185,
            "numberGoodReputation": 13,
            "numberOrders": 21,
            "numberReputation": 0,
            "numberSells": 16,
            "originalPrice": 490.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/07/11/df49fedd-1e93-49ec-b2a8-6eb9fb7c0579.jpg",
            "pingtuan": True,
            "pingtuanPrice": 0.00,
            "propertyIds": ",871,",
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 9998,
            "stores0Unsale": False,
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "videoId": "",
            "views": 107292,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "",
            "categoryId": 2246,
            "characteristic": "纯色袜子，适合5-7岁宝宝",
            "commission": 5.00,
            "commissionSettleType": 0,
            "commissionType": 2,
            "commissionUserType": 0,
            "dateAdd": "2017-10-30 10:33:36",
            "dateEnd": "2022-01-21 15:40:48",
            "dateEndCountDown": "7天",
            "dateEndPingtuan": "2021-01-16 00:00:00",
            "dateStart": "2022-01-01 15:40:46",
            "dateUpdate": "2022-01-13 21:07:51",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 6746,
            "kanjia": True,
            "kanjiaPrice": 1.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": True,
            "minBuyNumber": 1,
            "minPrice": 85.00,
            "minScore": 0,
            "name": "hellokitty童装 2019夏季新款儿童透气网眼女童棉袜中大童袜子",
            "numberFav": 33,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 120.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/07/11/f1097d87-6a36-485c-9e6c-c2cfb4291fd2.gif",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 999,
            "stores0Unsale": False,
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 15715,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "",
            "categoryId": 1872,
            "characteristic": "尼多熊袜子，适合秋冬天",
            "commission": 5.00,
            "commissionSettleType": 0,
            "commissionType": 2,
            "commissionUserType": 0,
            "dateAdd": "2017-10-30 10:31:27",
            "dateUpdate": "2022-01-13 21:30:51",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 6745,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 236.00,
            "minScore": 0,
            "name": "幼儿园园服韩版男女童装春秋季班服英伦学院风白色衬衫小学生校服",
            "numberFav": 118,
            "numberGoodReputation": 7,
            "numberOrders": 11,
            "numberReputation": 0,
            "numberSells": 9,
            "originalPrice": 500.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/07/11/e9fb59ae-7e66-427d-8d47-642c3b733a0b.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 5,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 45115,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "barCode": "",
            "categoryId": 2787,
            "characteristic": "保暖雨鞋",
            "commission": 5.00,
            "commissionSettleType": 0,
            "commissionType": 2,
            "commissionUserType": 0,
            "dateAdd": "2017-10-18 00:00:00",
            "dateStart": "2017-10-18 00:00:00",
            "dateUpdate": "2022-01-13 19:44:31",
            "fxType": 2,
            "gotScore": 11,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 5781,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 48.00,
            "minScore": 3,
            "name": "雨鞋",
            "numberFav": 29,
            "numberGoodReputation": 7,
            "numberOrders": 10,
            "numberReputation": 0,
            "numberSells": 7,
            "originalPrice": 58.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/07/05/748d7ea6-9aa0-4783-9f5d-3c05d4b3e166.gif",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 9999997,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "videoId": "",
            "views": 18927,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 2246,
            "characteristic": "拼色打底袜",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-25 09:26:09",
            "dateStart": "2017-09-25 09:22:26",
            "dateUpdate": "2022-01-13 16:59:40",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4517,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 459,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 12.00,
            "minScore": 0,
            "name": "可爱拼色打底袜",
            "numberFav": 16,
            "numberGoodReputation": 3,
            "numberOrders": 5,
            "numberReputation": 0,
            "numberSells": 3,
            "originalPrice": 25.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/38f2fd1c-1f2a-466c-b09a-185dcf98db75.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 104,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 13649,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 2246,
            "characteristic": "可开档的小童打底袜，中童尺码也有，小童6个月到24个月，中童4岁到8岁",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-25 09:19:24",
            "dateStart": "2017-09-25 09:15:10",
            "dateUpdate": "2022-01-11 19:36:43",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4512,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 459,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 20.00,
            "minScore": 0,
            "name": "打底袜",
            "numberFav": 10,
            "numberGoodReputation": 2,
            "numberOrders": 3,
            "numberReputation": 0,
            "numberSells": 2,
            "originalPrice": 30.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/74880087-c883-49f9-afe7-d5117283e61e.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 12577,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 2246,
            "characteristic": "可爱打底袜",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-25 09:14:55",
            "dateStart": "2017-09-25 09:10:58",
            "dateUpdate": "2022-01-13 15:15:37",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4510,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 459,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 12.00,
            "minScore": 0,
            "name": "可爱打底袜",
            "numberFav": 13,
            "numberGoodReputation": 2,
            "numberOrders": 3,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 25.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/2573dac9-e6eb-4f03-8577-acbf7a8cf96c.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 9442,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "中小童毛衣",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 09:47:58",
            "dateStart": "2017-09-24 09:43:08",
            "dateUpdate": "2022-01-13 16:49:39",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4470,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 49.00,
            "minScore": 0,
            "name": "毛衣",
            "numberFav": 63,
            "numberGoodReputation": 2,
            "numberOrders": 5,
            "numberReputation": 0,
            "numberSells": 2,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/1e3564a6-6646-40e7-9476-1281f4041245.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 22678,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "小狗图案毛衣",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 09:40:52",
            "dateStart": "2017-09-24 09:33:38",
            "dateUpdate": "2022-01-13 17:36:29",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4469,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 49.00,
            "minScore": 0,
            "name": "小狗图案毛衣",
            "numberFav": 42,
            "numberGoodReputation": 1,
            "numberOrders": 1,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/a613fd66-62ce-4c26-b5f4-0573b068f5b4.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "priceShopSell": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 106,
            "stores0Unsale": False,
            "type": 0,
            "unit": "份",
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 15019,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "小童毛衣背心",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 09:31:59",
            "dateStart": "2017-09-24 09:24:49",
            "dateUpdate": "2022-01-13 19:03:31",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4468,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 49.00,
            "minScore": 0,
            "name": "毛衣背心",
            "numberFav": 28,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/430932d8-e60b-42ef-988f-ac15e0d69df8.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 106,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 11688,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "小童爆款马甲，这个天气刚刚好穿",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 09:23:34",
            "dateStart": "2017-09-24 09:14:00",
            "dateUpdate": "2022-01-13 09:15:38",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4467,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 49.00,
            "minScore": 0,
            "name": "爆款背心",
            "numberFav": 16,
            "numberGoodReputation": 1,
            "numberOrders": 1,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/cabd5e5b-3ec3-48a9-9035-57098f878f2e.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 6771,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "多色可选的马甲",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 09:12:20",
            "dateStart": "2017-09-24 08:55:13",
            "dateUpdate": "2022-01-13 15:03:32",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4466,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 49.00,
            "minScore": 0,
            "name": "马甲",
            "numberFav": 10,
            "numberGoodReputation": 3,
            "numberOrders": 3,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/2071d45b-a68a-4852-a8de-df58955f1fdc.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 9624,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "可爱毛衣",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 08:53:48",
            "dateStart": "2017-09-24 08:48:14",
            "dateUpdate": "2022-01-12 12:09:56",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4464,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 3958,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "毛衣",
            "numberFav": 9,
            "numberGoodReputation": 2,
            "numberOrders": 2,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/64b2cbba-b3cd-4d9c-87e7-4fce4ffe3ec6.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 105,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 5767,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "女孩子喜欢的圈圈毛衣，加绒",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-24 08:41:37",
            "dateStart": "2017-09-24 08:35:52",
            "dateUpdate": "2022-01-13 16:16:34",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4463,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "毛衣",
            "numberFav": 6,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/aa3633df-62f2-4ff2-8773-ec546b4eabe4.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 56,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 5829,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "加绒毛衣，性价比高",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 16:10:49",
            "dateStart": "2017-09-22 16:06:03",
            "dateUpdate": "2022-01-13 17:51:47",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4411,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "加绒毛衣",
            "numberFav": 10,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/338e1ef3-c455-4873-ae9d-66ef22536251.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 56,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 4998,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "加绒毛衣，中大童",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 16:05:19",
            "dateStart": "2017-09-22 16:00:25",
            "dateUpdate": "2022-01-12 16:39:04",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4410,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "加绒毛衣",
            "numberFav": 9,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/5d19bb9b-4727-4fd3-9ab8-170ffde12bdc.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 56,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 5305,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "加绒毛衣，纯棉加绒款",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 15:59:55",
            "dateStart": "2017-09-22 15:54:02",
            "dateUpdate": "2022-01-12 19:32:21",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4409,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "加绒毛衣",
            "numberFav": 7,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/9ea289ce-9ce7-4a2a-9342-25ae4abfd3f3.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 56,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 3456,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "加绒毛衣，不久的北方就要穿到了",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 15:48:29",
            "dateStart": "2017-09-22 15:42:40",
            "dateUpdate": "2022-01-13 14:39:36",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4407,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 59.00,
            "minScore": 0,
            "name": "加绒毛衣",
            "numberFav": 9,
            "numberGoodReputation": 1,
            "numberOrders": 1,
            "numberReputation": 0,
            "numberSells": 1,
            "originalPrice": 89.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/26/69dd39f1-f7ad-49fd-8211-c9c7a3003c4a.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 56,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 3881,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "高品质的夹克外套",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 15:37:51",
            "dateStart": "2017-09-22 15:33:20",
            "dateUpdate": "2022-01-12 15:24:02",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4402,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 159.00,
            "minScore": 0,
            "name": "夹克外套",
            "numberFav": 7,
            "numberGoodReputation": 2,
            "numberOrders": 2,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 189.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/25/455e2434-ad8b-4bab-a4d7-724427b16228.gif",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 36,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 4510,
            "weight": 0.00
        },
        {
            "afterSale": "0,1,2",
            "categoryId": 1872,
            "characteristic": "貂绒毛衣，男孩女孩都适合",
            "commission": 0.00,
            "commissionSettleType": 0,
            "commissionType": 0,
            "commissionUserType": 0,
            "dateAdd": "2017-09-22 14:58:09",
            "dateStart": "2017-09-22 14:41:04",
            "dateUpdate": "2022-01-13 09:15:38",
            "fxType": 2,
            "gotScore": 0,
            "gotScoreType": 0,
            "hasAddition": False,
            "hasTourJourney": False,
            "hidden": 0,
            "id": 4391,
            "kanjia": False,
            "kanjiaPrice": 0.00,
            "limitation": False,
            "logisticsId": 386,
            "maxCoupons": 1,
            "miaosha": False,
            "minBuyNumber": 1,
            "minPrice": 139.00,
            "minScore": 0,
            "name": "貂绒毛衣",
            "numberFav": 18,
            "numberGoodReputation": 0,
            "numberOrders": 0,
            "numberReputation": 0,
            "numberSells": 0,
            "originalPrice": 189.00,
            "overseas": False,
            "paixu": 0,
            "pic": "https://cdn.it120.cc/apifactory/2019/06/25/344b8ae0-fb32-4752-bbec-7218ba887a17.jpg",
            "pingtuan": False,
            "pingtuanPrice": 0.00,
            "recommendStatus": 0,
            "recommendStatusStr": "普通",
            "seckillBuyNumber": 0,
            "sellEnd": False,
            "sellStart": True,
            "shopId": 0,
            "status": 0,
            "statusStr": "上架",
            "storeAlert": False,
            "stores": 36,
            "stores0Unsale": False,
            "type": 0,
            "unusefulNumber": 0,
            "usefulNumber": 0,
            "userId": 951,
            "vetStatus": 1,
            "views": 4904,
            "weight": 0.00
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class DiscountsCoupons(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        json_data = {
    "code": 0,
    "data": [
        {
            "batchSendUid": -1,
            "dateAdd": "2020-10-22 22:41:55",
            "dateEndDays": 30,
            "dateEndType": 1,
            "dateStartType": 1,
            "dateUpdate": "2021-08-31 19:52:26",
            "id": 8488,
            "moneyHreshold": 0.00,
            "moneyMax": 10.00,
            "moneyMin": 5.00,
            "moneyType": 1,
            "name": "测试比例优惠券",
            "needAmount": 0.00,
            "needScore": 0,
            "needSignedContinuous": 0,
            "numberGit": 8,
            "numberGitNumber": 1,
            "numberLeft": 892,
            "numberPersonMax": 10,
            "numberTotle": 900,
            "numberUsed": 0,
            "pwd": "Y",
            "sendBirthday": False,
            "sendInviteM": False,
            "sendInviteS": False,
            "sendRegister": False,
            "showInFront": True,
            "status": 0,
            "statusStr": "正常"
        },
        {
            "batchSendUid": -1,
            "dateAdd": "2019-08-07 14:50:54",
            "dateEndDays": 7,
            "dateEndType": 1,
            "dateStartType": 1,
            "dateUpdate": "2021-08-31 19:52:29",
            "id": 5453,
            "moneyHreshold": 0.00,
            "moneyMax": 1.00,
            "moneyMin": 1.00,
            "moneyType": 0,
            "name": "一人一份",
            "needAmount": 0.00,
            "needScore": 0,
            "needSignedContinuous": 0,
            "numberGit": 1311,
            "numberGitNumber": 1305,
            "numberLeft": 999999995,
            "numberPersonMax": 1,
            "numberTotle": 999999999,
            "numberUsed": 2,
            "pwd": "Y",
            "sendBirthday": False,
            "sendInviteM": False,
            "sendInviteS": False,
            "sendRegister": False,
            "showInFront": True,
            "status": 0,
            "statusStr": "正常"
        },
        {
            "batchSendUid": -1,
            "dateAdd": "2017-09-16 17:00:46",
            "dateEndDays": 15,
            "dateEndType": 1,
            "dateStartType": 1,
            "dateUpdate": "2022-01-13 11:33:18",
            "id": 223,
            "moneyHreshold": 3000.00,
            "moneyMax": 40.00,
            "moneyMin": 40.00,
            "moneyType": 0,
            "name": "新店优惠",
            "needAmount": 0.00,
            "needScore": 0,
            "needSignedContinuous": 0,
            "numberGit": 15447,
            "numberGitNumber": 8004,
            "numberLeft": 990564,
            "numberPersonMax": 999999,
            "numberTotle": 995699,
            "numberUsed": 64,
            "sendBirthday": False,
            "sendInviteM": False,
            "sendInviteS": False,
            "sendRegister": False,
            "showInFront": True,
            "status": 0,
            "statusStr": "正常",
            "type": ""
        },
        {
            "batchSendUid": -1,
            "dateAdd": "2017-09-16 17:00:05",
            "dateEndDays": 15,
            "dateEndType": 1,
            "dateStartType": 1,
            "dateUpdate": "2022-01-13 11:33:20",
            "id": 222,
            "moneyHreshold": 2000.00,
            "moneyMax": 25.00,
            "moneyMin": 25.00,
            "moneyType": 0,
            "name": "新店优惠",
            "needAmount": 0.00,
            "needScore": 0,
            "needSignedContinuous": 0,
            "numberGit": 12993,
            "numberGitNumber": 6433,
            "numberLeft": 998170,
            "numberPersonMax": 999999,
            "numberTotle": 999999,
            "numberUsed": 64,
            "sendBirthday": False,
            "sendInviteM": False,
            "sendInviteS": False,
            "sendRegister": False,
            "showInFront": True,
            "status": 0,
            "statusStr": "正常",
            "type": ""
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class NoticeList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def post(self, request):
        json_data = {
    "code": 0,
    "data": {
        "totalRow": 1,
        "totalPage": 1,
        "dataList": [
            {
                "dateAdd": "2017-09-16 17:20:43",
                "dateUpdate": "2019-03-18 11:05:17",
                "id": 161,
                "isShow": True,
                "title": "商城新开张，优惠多多，戳 戳 戳 我看详情。",
                "userId": 951
            }
        ]
    },
    "msg": "success"
}
        return Response(json_data)


class WxLiveRooms(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        json_data = {
    "code": 0,
    "data": [
        {
            "close_comment": 0,
            "close_kf": 1,
            "is_feeds_public": 1,
            "anchor_name": "梦佳",
            "close_like": 0,
            "end_time": 1617977069,
            "goods": [
                {
                    "price": 4500,
                    "name": "大理原产沃柑 现摘现发",
                    "price_type": 1,
                    "goods_id": 4,
                    "cover_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7icGKBgc8oDZ1AcIdNXWeGe5hIzvx6C7QaOlCTASbpvmM3rBnmQyhcsdLrwibgaAJnxP1M5QIVI36g/0",
                    "url": "pages/goods-details/index?id= 807491",
                    "third_party_appid": "",
                    "price2": 0
                }
            ],
            "live_type": 0,
            "roomid": 15,
            "feeds_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7icGKBgc8oDZ1AcIdNXWeGekK2njKvicXLz0iaI3kuMqD9W1FJDs0jb2lR0N4L6mjIxw8w69fw9LjJA/0",
            "start_time": 1617969587,
            "creater_openid": "om3AQ0YaRp3RZtFuZ1Wgk0OdQjvA",
            "name": "沃柑新上市 尝鲜正当时 美女来直播",
            "close_replay": 0,
            "share_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7icGKBgc8oDZ1AcIdNXWeGe5hIzvx6C7QaOlCTASbpvmM3rBnmQyhcsdLrwibgaAJnxP1M5QIVI36g/0",
            "cover_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7icGKBgc8oDZ1AcIdNXWeGeT1mmvlXFlJIGiab8SPaVQiabMnHBVibfVplAsgBpUJQC8RUcjibEBYTbYA/0",
            "close_goods": 0,
            "live_status": 103
        },
        {
            "close_comment": 0,
            "close_kf": 1,
            "is_feeds_public": 0,
            "anchor_name": "主播昵称",
            "close_like": 0,
            "end_time": 1611062147,
            "goods": [
                {
                    "price": 9900,
                    "name": "儿童睡衣男童短袖纯棉",
                    "price_type": 1,
                    "goods_id": 3,
                    "cover_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7R4icoWXqQTU5L1yKiawJFPcZK9k6eJ8SXBQGgZrmLAaDLkkj4YPYUUZfjEE7fBj9memrvcwH88XaA/0",
                    "url": "pages/goods-details/index?id=6761",
                    "third_party_appid": "",
                    "price2": 0
                }
            ],
            "live_type": 0,
            "roomid": 13,
            "feeds_img": "http://mmbiz.qpic.cn/mmbiz_png/EtdfuZTLxu7kU8wW1ibBHBko7sSemBMfNBXtiag00JhDRYsy3X7bJpDiahNiaoPdernMQjCoGgaIrXr1A9TKFYK5pA/0",
            "start_time": 1610975818,
            "creater_openid": "om3AQ0YaRp3RZtFuZ1Wgk0OdQjvA",
            "name": "测试直播",
            "close_replay": 1,
            "share_img": "http://mmbiz.qpic.cn/mmbiz_png/EtdfuZTLxu7kU8wW1ibBHBko7sSemBMfNHSs8jJIjJHX7cnOFm7FdMcuVyhundGbyYHgUjukgS9DHralabmnLYg/0",
            "cover_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu7kU8wW1ibBHBko7sSemBMfNc9ohbThxf9n8ib6d1zE3lMUyu9YuQ9o7zuCia1F3vjT3FCgkJRZ0cE9A/0",
            "close_goods": 0,
            "live_status": 107
        },
        {
            "close_comment": 0,
            "close_kf": 1,
            "is_feeds_public": 1,
            "anchor_name": "丫丫",
            "close_like": 0,
            "end_time": 1594393200,
            "goods": [],
            "live_type": 0,
            "roomid": 12,
            "feeds_img": "",
            "start_time": 1594342800,
            "creater_openid": "om3AQ0UZPWgqCUNcFWuYw3Wtq-tk",
            "name": "7月半全民购直播",
            "close_replay": 0,
            "share_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu5vjHvWm3LZicLbRiaCjnCHILBFXqtFoLLicf4StoI0110L8dufJbjCzhJe8YqBTVT9PbfLzbE12B9bw/0",
            "cover_img": "http://mmbiz.qpic.cn/mmbiz_jpg/EtdfuZTLxu5vjHvWm3LZicLbRiaCjnCHILBgOfkPSn5BoIpDAllebCND3E3gp5KQHSvSyPZMRnwWo1LV62Ysnaqg/0",
            "close_goods": 0,
            "live_status": 107
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class SiteAdPositionInfo(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        key = request.query_params.get('key', 'indexPop')  # 'index-live-pic'
        json_data = {
    "code": 0,
    "data": {
        "name": "首页弹出广告",
        "type": "pic",
        "val": "https://7.s2m.cc/2022/01/01/419a797b-bcd7-4d31-976f-7b97231223b0.jpeg"
    },
    "msg": "success"
}
        return Response(json_data)


class SiteGoodsDynamic(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        type_str = request.query_params.get('type', '0')
        json_data = {
    "code": 0,
    "data": [
        {
            "nick": "okay",
            "uid": 2502791,
            "number": 1,
            "orderId": 1283659,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaEJgHInNERVKpLCxgfLe9QWUk42mAvFPwchCSFvNrfkT0zuMeM5ic9c8gqpo00BcFGpNdBxtpZ2RmhA/132",
            "dateAdd": "2022-01-13 15:58:35",
            "goodsId": 6761,
            "goodsName": "儿童睡衣男童短袖纯棉夏季薄款男孩中大童卡通宝宝家居服套装夏天"
        },
        {
            "nick": "蕾子",
            "uid": 2017654,
            "number": 1,
            "orderId": 1283544,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIqqIzbIXdONjn5yTCtJU6ONiaR6WtFTibXbFibKBHLjPnsq2Dd4hG1UcERbqTM5yvrVZotiboB10MRzw/132",
            "dateAdd": "2022-01-13 14:29:21",
            "goodsId": 235853,
            "goodsName": "3分钟沙漏「儿童刷牙计时器」"
        },
        {
            "nick": "徐崇",
            "uid": 1969851,
            "number": 1,
            "orderId": 1283041,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqcKVsJFicdH7Ot7lOwibodz1lH3gbqL5HANzvyCrQvqxtqAEfgPLPKnEdtN1YEUHH1RBSKSuuXiaA9Q/132",
            "dateAdd": "2022-01-12 21:29:03",
            "goodsId": 435060,
            "goodsName": "WiFi云标签机 FP-N20W"
        },
        {
            "nick": "快⃰乐⃰的⃰废⃰物⃰",
            "uid": 2484029,
            "number": 1,
            "orderId": 1282810,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIwY1mhUqD8PzsqfvkpeQjh9y3mtbfg1AiclIsWuyqhYY1hCaqmVe9ceIAhwNENsCfqIT8nH0wf5Fw/132",
            "dateAdd": "2022-01-12 17:56:01",
            "goodsId": 4470,
            "goodsName": "毛衣"
        },
        {
            "nick": "控",
            "uid": 2510913,
            "number": 1,
            "orderId": 1282353,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLQWsRVibEribE1qBu42xCMrlLZGrCibfTic410x35iayqlx9OQ92M5aKyR3AK1OMkub8RvwmiaBFHeiaVxQ/132",
            "dateAdd": "2022-01-12 12:26:20",
            "goodsId": 6761,
            "goodsName": "儿童睡衣男童短袖纯棉夏季薄款男孩中大童卡通宝宝家居服套装夏天"
        },
        {
            "nick": "猴",
            "uid": 2508815,
            "number": 1,
            "orderId": 1282169,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/aNAghTMSOD8iatAAdtMJzoDqxVQDzokyvyoljesY7aIvWVQicC9GUGv5vr0HHMYKAE0DyRIWMQTBmlH0S3x4yo4A/132",
            "dateAdd": "2022-01-12 10:40:56",
            "goodsId": 6745,
            "goodsName": "幼儿园园服韩版男女童装春秋季班服英伦学院风白色衬衫小学生校服"
        },
        {
            "nick": "阿白",
            "uid": 2458956,
            "number": 1,
            "orderId": 1281729,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q3auHgzwzM6D57P62xSZmEKYjz0gnF4tR2YbhhqYzuo5Y5O4h4rUn92unNEmnpKFIOgsrRJdFrsFJUrPcbqb2A/132",
            "dateAdd": "2022-01-11 23:30:07",
            "goodsId": 4470,
            "goodsName": "毛衣"
        },
        {
            "nick": "阿白",
            "uid": 2458956,
            "number": 1,
            "orderId": 1281728,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q3auHgzwzM6D57P62xSZmEKYjz0gnF4tR2YbhhqYzuo5Y5O4h4rUn92unNEmnpKFIOgsrRJdFrsFJUrPcbqb2A/132",
            "dateAdd": "2022-01-11 23:30:01",
            "goodsId": 4470,
            "goodsName": "毛衣"
        },
        {
            "uid": 2509606,
            "number": 1,
            "orderId": 1281660,
            "dateAdd": "2022-01-11 21:38:36",
            "goodsId": 6746,
            "goodsName": "hellokitty童装 2019夏季新款儿童透气网眼女童棉袜中大童袜子"
        },
        {
            "nick": "玉峰",
            "uid": 2509068,
            "number": 2,
            "orderId": 1281346,
            "avatarUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLPK5hKCdicXsoJHaMX1Nv39wr0X1wgOC2QdtlkDaJb3jPgIxTKTJVxSRLg6OlsGnRTZ1TpCKjrichQ/132",
            "dateAdd": "2022-01-11 18:05:23",
            "goodsId": 810285,
            "goodsName": "小票打印机工厂定制版"
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class ShopGoodsKanJiaSetV2(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request):
        goods_id = request.query_params.get('goodsId', '6765%2C6746')
        json_data = {
    "code": 0,
    "data": [
        {
            "dateAdd": "2018-04-01 17:10:19",
            "dateEnd": "2222-05-01 12:00:00",
            "goodsId": 6765,
            "helpPriceMax": 10.00,
            "helpPriceMin": 1.00,
            "helpTimes": 2,
            "id": 3,
            "minPrice": 82.00,
            "number": 676500,
            "numberBuy": 121,
            "originalPrice": 100.00,
            "reduction": False,
            "status": 0,
            "statusStr": "正常"
        }
    ],
    "msg": "success"
}
        return Response(json_data)


class TestViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Goods.objects.all()
    serializer_class = GoodsSerializer
    pagination_class = ShortResultsSetPagination
    permission_classes = []


